#region ------ [ Framework-Level Provider / Identity Variables ] ------------------------- #

variable "environment_prefix" {
  type        = string
  default     = "demo"
  description = "Prefix prepended to every generated artifact (file names, Terraform resource addresses, output identifiers). Lets multiple deployments of this framework coexist in one workspace without collision."

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{0,15}$", var.environment_prefix))
    error_message = "environment_prefix must be lowercase, start with a letter, contain only [a-z0-9-], and be 1-16 characters."
  }
}

variable "global_tag" {
  type        = string
  default     = "framework-example"
  description = "Free-form label applied to every synthetic resource as a `triggers` map entry or tag attribute. Used by tests to assert resources came from the expected apply."
}

variable "secret_seed" {
  type        = string
  sensitive   = true
  default     = null
  description = "Optional sensitive salt hashed into every generated random_string keeper. Changing it rotates generated random strings without storing the raw value in state. Inject via terraform.tfvars or a TF_VAR_secret_seed environment variable; do not commit real secrets."
}

#endregion --- [ Framework-Level Provider / Identity Variables ] ------------------------- #

#region ------ [ Synthetic Environments: list(object({...})) Mega-Variable ] -------------- #

variable "all_environments" {
  description = "Every synthetic environment this framework should produce. Each entry expands (in locals.tf) to a bundle of synthetic resources demonstrating the framework pattern: required + optional scalars, list-of-objects with iterative dynamic blocks, single-optional with splat-on-optional dynamic blocks, and tier-based defaults injected via the data-source-injection pattern."

  type = list(
    object({

      /* Required Parameters */
      name  = string
      owner = string
      tier  = string

      /* Optional Parameters */
      enabled        = optional(bool, true)
      retention_days = optional(number)
      # ^ Default deliberately ABSENT here. Defaulting happens in locals.tf
      # using data.local_file.tier_defaults so per-tier defaults are
      # applied. Demonstrates "computed default from data source" pattern.
      description = optional(string)
      tags        = optional(list(string), [])

      manifests = optional(
        list(
          object({

            /* Required Parameters */
            filename = string
            content  = string

            /* Optional Parameters */
            permissions      = optional(string, "0644")
            directory_create = optional(bool, true)
          })
        )
      )
      lifecycle_hooks = optional(
        list(
          object({

            /* Required Parameters */
            name = string

            /* Optional Parameters */
            triggers = optional(map(string), {})
            # description: use triggers["description"] instead; null_resource has no native description.
          })
        )
      )
      # rotation: single optional block exercising the splat-on-optional dynamic pattern.
      rotation = optional(
        object({
          rotation_days  = optional(number)
          rotation_hours = optional(number)
          # rotation_minutes: omitted intentionally; sub-hour rotation is non-idiomatic for this showcase.
          # triggers: pulled from environment.tags + global_tag at locals expansion.
        })
      )
      pet = optional(
        object({
          length = optional(number)
          # ^ Default deliberately ABSENT — comes from tier_defaults.default_pet_length
          separator = optional(string, "-")
          prefix    = optional(string)
          # length_override: see `pet.length`; explicit override wins over tier default.
        })
      )
      # certificate: single optional block with a nested optional subject block.
      certificate = optional(
        object({

          /* Optional Parameters */
          validity_period_hours = optional(number, 720) # 30 days
          early_renewal_hours   = optional(number)
          is_ca_certificate     = optional(bool, false)
          set_subject_key_id    = optional(bool, false)
          allowed_uses = optional(list(string), [
            "key_encipherment",
            "digital_signature",
            "server_auth",
          ])
          # private_key_pem: generated by tls_private_key in main.tf; never accepted from input.

          subject = optional(
            object({
              common_name         = optional(string)
              country             = optional(string)
              locality            = optional(string)
              organization        = optional(string)
              organizational_unit = optional(string)
              postal_code         = optional(string)
              province            = optional(string)
              serial_number       = optional(string)
              street_address      = optional(list(string))
            })
          )
        })
      )
    })
  )

  validation {
    condition     = length(var.all_environments) >= 1
    error_message = "all_environments must contain at least one environment."
  }

  validation {
    condition     = alltrue([for e in var.all_environments : can(regex("^[a-z][a-z0-9-]{0,31}$", e.name))])
    error_message = "Each environment.name must be lowercase, start with a letter, contain only [a-z0-9-], and be 1-32 characters."
  }

  validation {
    condition     = alltrue([for e in var.all_environments : contains(["dev", "staging", "prod"], e.tier)])
    error_message = "Each environment.tier must be one of: dev, staging, prod."
  }

  validation {
    condition     = length(distinct([for e in var.all_environments : e.name])) == length(var.all_environments)
    error_message = "Environment names must be unique within all_environments."
  }

  validation {
    condition = alltrue(flatten([
      for e in var.all_environments : [
        for m in coalesce(e.manifests, []) :
        can(regex("^0?([0-5][0-7][0-7]|6[0-3][0-7]|64[0-4])$", m.permissions))
      ]
    ]))
    error_message = "Manifest permissions must be no more permissive than 0644."
  }

  validation {
    condition = alltrue([
      for e in var.all_environments :
      e.certificate == null ? true : e.certificate.validity_period_hours <= 8760
    ])
    error_message = "Certificate validity_period_hours must be <= 8760."
  }

  validation {
    condition = alltrue([
      for e in var.all_environments :
      e.certificate == null ? true : e.certificate.is_ca_certificate == false
    ])
    error_message = "Synthetic environment certificates must not be CA certificates."
  }
}

#endregion --- [ Synthetic Environments: list(object({...})) Mega-Variable ] -------------- #
